{% set name = "openscenegraph-osgQt" %}
{% set version = "3.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/openscenegraph/osgQt/archive/{{ version }}.tar.gz
    sha256: dcc4436590639168e6470fe9c5343c82bca738d3296ebee014f40f2dc029afa1
    patches:
    - patches/qt5_modern.patch
  - path: examples_data
    folder: examples_data

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
  host:
    - openscenegraph
    - qt-main

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}5
    - test -f $PREFIX/include/osgQt/GraphicsWindowQt

about:
  home: http://github.com/openscenegraph/osgQt
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'OpenSceneGraph Qt integration library'
  description: |
    OpenSceneGraph Qt integration library
  doc_url: http://www.openscenegraph.org/index.php/documentation
  dev_url: http://github.com/openscenegraph/osgQt

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
