{% set name = "openscenegraph-osgQt" %}
{% set version = "3.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/openscenegraph/osgQt/archive/{{ version }}.tar.gz
    sha256: dcc4436590639168e6470fe9c5343c82bca738d3296ebee014f40f2dc029afa1
    patches:
    - patches/qt5_modern.patch
    - patches/osx_fix_architecture.patch  # [osx]
  - path: examples_data
    folder: examples_data

build:
  number: 6
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - qt-main  # [build_platform != target_platform]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
  host:
    - openscenegraph
    - qt-main
    - xcb-util                           # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-xf86vidmodeproto              # [linux]
  run:
    - libxcb                             # [linux]
    - xcb-util-wm                        # [linux]
    - xcb-util-keysyms                   # [linux]
    - xcb-util-image                     # [linux]
    - xcb-util-renderutil                # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libsm                         # [linux]
    - xorg-libice                        # [linux]
    - xorg-xf86vidmodeproto              # [linux]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}5
    - test -f $PREFIX/include/osgQt/GraphicsWindowQt

about:
  home: http://github.com/openscenegraph/osgQt
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: OpenSceneGraph Qt integration library
  description: |
    OpenSceneGraph Qt integration library
  doc_url: http://www.openscenegraph.org/index.php/documentation
  dev_url: http://github.com/openscenegraph/osgQt

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
